# Model configuration
pretrained_model_name: "clip-ViT-B-32"
name: "bge-base-en-v1.5-futo-swipe-base"

# Model architecture parameters
max_seq_length: 512
do_lower_case: false
matryoshka_dims: [64, 128, 256, 512]


# Training-specific model parameters
use_marker_tokens: true
marker_start: "[START]"
marker_end: "[END]"


